airflow:
  redis:
    password: "password"
  auth:
    password: "password"
  postgresql:
    auth:
      password: "password"
keycloak:
  service:
    type: "LoadBalancer"
    loadBalancerIP: "192.168.1.250"
